### ISSUE TITLE
mod doesn't work with Aquacutures fishing rods/bobbers

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [quervyloll/AutoFish#1]
Hi there, 

When I tried to put in the command /autofish true a message popped up saying you must be holding a fishing rod. I'm guessing this wasn't intended to work with modded fishing rods and only unmodded fishing rods?

Minecraft 1.21.1 
NeoForge: 21.1.66 
AutoFish: 1.1.1 
Aquaculture: 2.7.10
Forge-ified Fabric API: 0.104.0-2.0.15
Connector: 2.0.0.beta-3
Connector Extras: 1.12.1

**Comment by quervyloll** [comment]
yes that is correct, ill make a new branch without the need to hold a fishing rod in a bit

**Comment by DatrixTheHybridShadowWolf** [comment]
Thanks!
